name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install -g htmlhint stylelint stylelint-config-standard

      - name: Lint HTML Files
        run: htmlhint "src/**/*.html"

      - name: Lint CSS Files
        run: stylelint "styles/**/*.css"

  build:
    name: Build Website
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install -g parcel

      - name: Build Project
        run: parcel build src/index.html